apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi