apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  name: nginx
  namespace: default
spec:
  rules:
  - host: "nginx.localhost"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
            service:
              name: nginx
              port:
                number: 80
